### ISSUE TITLE
Make informative error when schema mismatch with data columns

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AncientMetagenomeDirCheck#10]
When there are misnamed columns (i.e. a column doens't match the one in the schema), this can cause a lot of pythony traceback errrs, e.g. in https://github.com/SPAAM-community/AncientMetagenomeDir/pull/297/checks?check_run_id=1231360705

A nice check would be 'do you have the correct number of columns' and 'do you have all the expected headers'.

**Comment by maxibor** [comment]
Fixed with version 1.2.1
