### ISSUE TITLE
Identify whether submitted DOI is duplicate

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AncientMetagenomeDirCheck#11]
I made the mistake the other day (due to getting the first author wrong), of making a duplicate PR of a paper that was already there.

Maybe we could add a check to compare the new DOI in a PR against the list already in the master branch (e.g. how you check the enums)? Maybe a `git diff` system could be used to identify the new DOI or not (assuming it's a new submission)?

**Comment by maxibor** [comment]
Note for future self: Could be done with [PyGitHub]()https://pygithub.readthedocs.io/en/latest/examples/Repository.html#get-a-specific-content-file

**Comment by jfy133** [comment]
Simplest (with a R/tidyverse brain) would be doing a `unique` or `distinct` on the project_name and the DOI, and _then_ check for duplicate DOIs in the DOI column.

i.e. if you have two different project_names but with the same DOI, this should get flagged

**Comment by maxibor** [comment]
Done with e7f3b39a1f6128c26246d64b95d60d1d1dd57a15
