### ISSUE TITLE
Check craps out if extra empty columns at the end of a row

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AncientMetagenomeDirCheck#21]
Rush issue from my phone.

Add a few extra tabs to the end of valid line and check breaks with pandas error and no bot comment

**Comment by maxibor** [comment]
> If a line has extra tabs at the end (basically 'empty' columns) we get a PANDAS error it seems despite the 'check extra missing columns'.
https://github.com/SPAAM-community/AncientMetagenomeDir/runs/4541321193?check_suite_focus=true

**Comment by maxibor** [comment]
Added a check for that
